
server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: c:/upload
      enable: true
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    hidden-method:
      filter:
        enabled: true
  profiles:
    active:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

mybatis:
  mapper-locations: com.example.demo/mapper/*.xml
  type-aliases-package: com.example.demo.dto

http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
